# Generated by Django 3.2.13 on 2022-05-24 13:08

import apps.participant.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_archived', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_archived', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('is_first_time', models.BooleanField(default=False, help_text='Is this first time participating in Sharjah Excellence Award ?.')),
                ('category_id', models.BigIntegerField(db_index=True)),
                ('category_name', models.CharField(db_index=True, max_length=255)),
                ('organization_type', models.CharField(choices=[('private', 'Private'), ('government', 'Government')], db_index=True, max_length=10)),
                ('organization_location', models.CharField(choices=[('abu_dhabi', 'Abu Dhabi'), ('dubai', 'Dubai'), ('sharjah', 'Sharjah'), ('ajman', 'Ajman'), ('umm_al_quwain', 'Umm Al Quwain'), ('ras_al_khaimah', 'Ras Al Khaimah'), ('fujairah', 'Fujairah'), ('oman', 'Oman'), ('saudi_arabia', 'Saudi Arabia'), ('qatar', 'qatar'), ('kuwait', 'Kuwait'), ('bahrain', 'Bahrain')], db_index=True, max_length=14)),
                ('organization_name', models.CharField(max_length=255)),
                ('organization_number_of_employees', models.BigIntegerField()),
                ('contact_person_name', models.CharField(max_length=255)),
                ('contact_person_number', models.CharField(max_length=255)),
                ('contact_person_email', models.EmailField(max_length=254)),
                ('secondary_contact_person_name', models.CharField(blank=True, max_length=255, null=True)),
                ('secondary_contact_person_number', models.CharField(blank=True, max_length=255, null=True)),
                ('secondary_contact_person_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('membership_certificate', models.FileField(blank=True, max_length=255, null=True, upload_to=apps.participant.utils.upload_membership_certificate_to)),
                ('trade_license', models.FileField(max_length=255, upload_to=apps.participant.utils.upload_trade_license_to)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
