# Generated by Django 3.2.13 on 2022-05-25 08:38

import apps.participant.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='trade_license',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=apps.participant.utils.upload_trade_license_to),
        ),
    ]
